### ISSUE TITLE
5.1节光纤惯导数据格式问题

### ISSUE THREAD

**Issue by quangWHU** [chichengcn/gici-open-dataset#10]
池老师您好，我按照您提供的imupack_to_text工具将5.1节光纤惯导数据转换为txt文件格式，前几行数据如下：
Timestamp	Acc-X	Acc-Y	Acc-Z	Gyro-X	Gyro-Y	Gyro-Z	
1684646035.102	  9.65450134	  0.01300964	 -0.04934692	 -0.000199737	 -0.000466053	  0.001731055
1684646035.103	  9.65450134	  0.01300964	 -0.04934692	 -0.000399474	 -0.001331581	  0.002729740
1684646035.104	  9.65450134	  0.01300964	 -0.04934692	 -0.000466053	 -0.002063950	  0.003595267
我有一些疑问想问下您：
首先，Timestamp代表的时间信息具体是什么意义？
其次，我看x轴输出的比力测量值接近重力，那么该光纤惯导的安装姿态与载体是什么关系？也就是该光纤惯导的XYZ三轴的朝向与小车是什么关系呀，一般来说应该是Z轴比力测量值接近重力如果Z轴朝上的话。

**Comment by chichengcn** [comment]
timestamp是unix时。

车载硬件之间的旋转平移关系见intrinsics_and_extrinsics.yaml，其中的body系的xyz分别是车运动方向的右前上。
你用fog原始数据的话需要注意一点，上述yaml文件中的fog坐标系指的是groundtruth文件的坐标系，而从groundtruth文件坐标系到fog原始数据坐标系有一个（0, 90, 0）的旋转，该旋转在使用IE处理的时候键入，可以在groundtruth文件的头部找到。

**Comment by quangWHU** [comment]
好的，谢谢池老师，我仔细思考一下
