### ISSUE TITLE
相机原始数据格式转换

### ISSUE THREAD

**Issue by quangWHU** [chichengcn/gici-open-dataset#12]
池老师您好，我想把原始相机输出的bin文件转换为MP4文件，请问该怎么做呢

**Comment by chichengcn** [comment]
我们提供了bin转照片的程序（见[imagepack_to_tum.cpp](https://github.com/chichengcn/gici-open/blob/master/tools/evaluation/format_converters/src/imagepack_to_tum.cpp)），从中你可以获取针对bin解码的源码，而后通过压制视频流的开源库（比如ffmpeg）进行MP4文件生成。
