### ISSUE TITLE
ROS接口实现如何选取数据集

### ISSUE THREAD

**Issue by Infinitivities** [chichengcn/gici-open-dataset#13]
在ros接口提供的配置文件中找不到输入数据的地址配置选项，想请问教授在通过ros进行解算时如何选取输入数据

**Comment by chichengcn** [comment]
ros模式下，只需要指定输入的topic即可，这个在我们给的示例yaml里已经提供了。数据通过rosbag play发送到这些topic上。

**Comment by Infinitivities** [comment]
如何把自己的数据转换成.bin格式的文件

**Comment by Infinitivities** [comment]
想再请问一下教授，自己的数据文件，比如gnss.log，还有星历的.o文件，这些文件怎么转换成框架所需的.bin文件呢
