### ISSUE TITLE
杆臂问题

### ISSUE THREAD

**Issue by XFactorN** [chichengcn/gici-open-dataset#15]
池博您好
1. 请问数据集5.1 ground truth文件位置结果是输出到光纤IMU中心吗？ground truth文件中所给的IMU-GNSS杆臂右向比前向大，但图中位置关系似乎是前向比右向大。按ie中显示的body系右前上（实际是GT系左前下）光纤IMU-GNSS的杆臂值似乎无法对应图中的位置关系
另外我在查看intrinsics_and_extrinsics.yaml时发现T_B_GT中的平移量 右向为毫米级 根据图中位置关系应该不只毫米级
**所给安装图片是否有误 根据杆臂关系 光纤IMU应该位于板载IMU的正后方32cm处**
2. **根据杆臂关系 ie文件中光纤IMU-GNSS的垂向杆臂应大致为0.0665+0.029=9.5厘米 而不是4.9厘米**

**Comment by chichengcn** [comment]
1. ground truth文件位置结果是光纤IMU中心，图片为示意图，实际安装与图片并非完全一致，应按照yaml文件中给出的数值进行处理。
2. yaml文件中给出的大部分参数为两两传感器之间的后处理估计值，一般来说，对于车载平台，通过GNSS/INS组合导航后处理计算杆臂值，在高程方向的标称误差为<5cm，9.5vs4.9的误差产生于此。

**Comment by XFactorN** [comment]
好的 谢谢池博
