### ISSUE TITLE
关于怎样测量APE

### ISSUE THREAD

**Issue by sxshenxue123** [chichengcn/gici-open-dataset#3]
感谢作者您的开源，我想测量几个不同开源项目的APE进行对比，目前我碰到了这个问题：我用项目里提供的tools中的工具将ground truth转换为了tum，并且将数据集源文件转换成了rosbag，如果我想使用evo工具来计算APE的话，我该怎样将rosbag也转换成tum格式？我在您的论文结尾看见了APE的对比图，很想知道是怎么计算APE的。（如能抽空回答，不胜感激）

**Comment by chichengcn** [comment]
我们在to_rosbag的程序中使用了bag.write接口，ros同样有bag.read接口，你可以使用此接口，以及我们to_tum的程序，自行撰写rosbag_to_tum的程序。
我们文章中的APE表格中的数据是用EVO计算的，APE曲线是用matlab画的，至于计算APE，就是保证两个轨迹坐标系相同的前提下，把时间插值到同一个点，计算误差即可。
