### ISSUE TITLE
help for check "Waiting for ephemeris. We still have..."

### ISSUE THREAD

**Issue by i-am-leilee** [chichengcn/gici-open-dataset#4]
thanks for sharing your great work. 

i succeeded to build and run the release version of code, non-ros mode.
and i downloaded some packs from this dataset site, like 1.2, 2.1, 3.2, 4.2

tests with `rtk_tc` and `rtk_rrr` apps, 
but most of results show **"Waiting for ephemeris. We still have xx satellites that do not have ephemeris."**, last long to the end of replaying.

i am not sure if something wrong with the option or the dataset
As in the option yaml file provided with code, i just replaced those directories to my own env.

please help check, thanks.

**Comment by chichengcn** [comment]
You might forget to modify the "start_time" options. 

The RTCM message does not record GPS week. Hence, if you do not specify the start time, the timestamps of the decoded data will be mismatched.

**Comment by i-am-leilee** [comment]
> You might forget to modify the "start_time" options.
> 
> The RTCM message does not record GPS week. Hence, if you do not specify the start time, the timestamps of the decoded data will be mismatched.

ah.. that works
thanks
