### ISSUE TITLE
Questions about data format

### ISSUE THREAD

**Issue by ZhouZineng** [chichengcn/gici-open-dataset#5]
I would like to inquire about the format of the data in gnss_rover.bin and gnss_reference.bin files in the dataset. From the code, I understand that they are parsed using RTKLIB's format_ == GnssRawFormats::Novatel. However, I'm still unclear about the specific format used in the binary files. Could you please provide me with more information regarding the binary file format? Your assistance would be greatly appreciated.

**Comment by chichengcn** [comment]
Rover is rangeb format，reference is rtcm3 format.
