### ISSUE TITLE
ros-based RTK_TC

### ISSUE THREAD

**Issue by Ganglee98** [chichengcn/gici-open-dataset#7]
Dear authors

I encountered a question about RTK_TC mode based on ROS environment. The question is as follow:

Initialized 9 streamers, 2 formaters, and 1 estimator. Running...
I20230926 17:44:45.784895 15695 formator.cpp:1266] Input DCBs are not closed for R06
I20230926 17:44:45.785063 15695 formator.cpp:1266] Input DCBs are not closed for R10
I20230926 17:44:45.785478 15695 formator.cpp:1266] Input DCBs are not closed for R23

It can not go on. Did something wrong I configure? I have used the tools transferring the raw files to rosbag format.

stream:
  streamers:
    - streamer:
        tag: str_ros_gnss_rov
        type: ros
        topic_name: /gici/gnss_rover
        io: input
        format: gnss_raw
        enable_observation: true
    - streamer:
        tag: str_ros_gnss_ref
        type: ros
        topic_name: /gici/gnss_reference
        io: input
        format: gnss_raw
        enable_observation: true
        enable_antenna_position: true
    - streamer:
        tag: str_ros_gnss_eph
        type: ros
        topic_name: /gici/gnss_ephemeris
        io: input
        format: gnss_raw
        enable_ephemeris: true
        enable_ionosphere_parameter: true
    - streamer:
        tag: str_dcb_file
        output_tags: [fmt_dcb_file]
        type: file
        path: /home/.../Downloads/GICI/gici/option/CAS0MGXRAP_20221580000_01D_01D_DCB.BSX
        enable_time_tag: false
    - streamer:
        tag: str_ros_imu
        type: ros
        topic_name: /gici/imu_raw
        io: input
        format: imu
    - streamer:
        tag: str_tc_solution_file
        input_tags: [fmt_tc_solution_file]
        type: file
        path: /home/.../Downloads/GICI/gici/ros_wrapper/src/gici/out_res/52/rtk_tc_solution.txt
        enable_time_tag: false
    - streamer:
        tag: str_solution
        type: ros
        topic_name: solution
        queue_size: 5
        io: output
        format: pose_stamped
    - streamer:
        tag: str_solution_odometry
        type: ros
        topic_name: solution_odometry
        queue_size: 10
        io: output
        format: odometry
        subframe_id: Body
    - streamer:
        tag: str_solution_path
        type: ros
        topic_name: solution_path
        queue_size: 100
        io: output
        format: path
  
  formators:
    - formator:
        io: input
        tag: fmt_dcb_file
        type: dcb-file
    - formator:
        io: output
        tag: fmt_tc_solution_file
        type: nmea 
        use_esa: true
        talker_id: GP

  replay:
    enable: false

estimate:
- estimator:
    tag: est_rtk_imu_tc
    type: rtk_imu_tc
    input_tags: [str_ros_gnss_rov, str_ros_gnss_ref, str_ros_gnss_eph, fmt_dcb_file, str_ros_imu]
    str_ros_gnss_rov_roles: [rover]
    str_ros_gnss_ref_roles: [reference]
    str_ros_gnss_eph_roles: [ephemeris]
    fmt_dcb_file_roles: [code_bias]
    str_ros_imu_roles: [major]
    output_tags: [fmt_tc_solution_file, str_solution, str_solution_odometry, str_solution_path]
    output_align_tag: str_ros_imu
    output_downsample_rate: 40
    compute_covariance: true
    rtk_imu_tc_options:
      max_window_length: 3
    rtk_options:
      use_ambiguity_resolution: true
    gnss_estimator_base_options:
      use_outlier_rejection: true
      reject_one_outlier_once: false
      max_pesudorange_error: 4.0      
      max_phaserange_error: 0.06      
      max_doppler_error: 0.5
      gnss_common:
        min_elevation: 12.0           
        min_SNR: [35.0, 30.0]
    imu_estimator_base_options:
      imu_parameters:
        sigma_bg: 1.0e-3
        sigma_ba: 1.0e-2
        sigma_g_c: 2.6700e-04
        sigma_a_c: 0.0112
        sigma_gw_c: 2.0881e-06
        sigma_aw_c: 2.7361e-04
      body_to_imu_rotation: [-90.0, -90.0, 0.0]
      body_to_imu_rotation_std: 5.0
      car_motion: true
      car_motion_min_velocity: 3.0
      car_motion_max_anguler_velocity: 5.0
    estimator_base_options:
      max_iteration: 5
      num_threads: 4
      max_solver_time: 0.05
      verbose_output: true
      solver_type: dense_schur
      trust_region_strategy_type: dogleg
    ambiguity_resolution_options:
      system_exclude: [R]
      min_percentage_fixation_uwl: 1.0
      min_percentage_fixation_wl: 0.9
      min_percentage_fixation_nl: 0.9
      ratio: 2.0
    gnss_imu_initializer_options:
      max_iteration: 30
      num_threads: 4
      max_solver_time: 0.5
      gnss_extrinsics: [-0.029, 0.354, -0.042]
      gnss_extrinsics_initial_std: [0.0, 0.0, 0.0]
      time_window_length_slow_motion: 0.05
      time_window_length_dynamic_motion: 0.5
      min_acceleration: 0.5

logging:
  enable: true
  min_log_level: 0
  log_to_stderr: true
  file_directory: <log-directory>

**Comment by chichengcn** [comment]
You should play the rosbags after the gici_ros_main is started.
