### ISSUE TITLE
关于GNSS数据格式及转换的问题

### ISSUE THREAD

**Issue by ZhouZineng** [chichengcn/gici-open-dataset#8]
尊敬的开发者，

我们目前正在使用GNSS数据，并对数据格式和转换有一些疑问。

我们对gnss_ephemeris.bin文件的采集细节感到好奇。您能否提供更多关于采集过程、所使用的工具以及设定的参数等信息？

我们正在使用UB482作为流动站，这只允许我们采集RINEX格式的星历信息。我们需要将这些数据转换为RTCM3格式。请问您知道如何进行这种转换吗？因为在互联网上我们没有找到现成的转换工具，所以前来寻求帮助。

期待您的回复，感谢您的时间和帮助。

**Comment by chichengcn** [comment]
关于数据格式和采集方式，请参考我们的manual。

UB482支持RTCM3输出，以及Novatel输出（RangeB, EphemrisB），的实时输出，请参考该模块的使用手册。

关于Rinex的接口，由于它不是实时文件格式，所以不易集成在当前的GICI流程中。我们正在开发，预计年底之前会发出来。如果你想要近期自己写一个Rinex to rtcm3的软件，可以参考RTKLIB的Rinex解码和rtcm3编码。
